import { Lexer } from '../../syntax/lexing/lexer.js';

export const lexer = new Lexer()
	.add_value_lexeme('whitespace', ' ')
	.add_value_lexeme('tab', '\t')
	.add_pattern_lexeme('newline', /^\r?\n/)
	.add_value_lexeme('underscore', '_')
	.add_value_lexeme('hyphen', '-')
	.add_value_lexeme('plus', '+')
	.add_value_lexeme('star', '*')
	.add_value_lexeme('percent', '%')
	.add_value_lexeme('forward-slash', '/')
	.add_value_lexeme('back-slash', '\\')
	.add_value_lexeme('tilde', '~')
	.add_value_lexeme('semi-colon', ';')
	.add_value_lexeme('colon', ':')
	.add_value_lexeme('back-tick', '`')
	.add_value_lexeme('open-paren', '(')
	.add_value_lexeme('close-paren', ')')
	.add_value_lexeme('open-square', '[')
	.add_value_lexeme('close-square', ']')
	.add_value_lexeme('open-curly', '{')
	.add_value_lexeme('close-curly', '}')
	.add_value_lexeme('colon', ':')
	.add_value_lexeme('squiggle', '~')
	.add_value_lexeme('exclamation', '!')
	.add_value_lexeme('pipe', '|')
	.add_pattern_lexeme('letter<lower>', /^[a-z]/)
	.add_pattern_lexeme('letter<upper>', /^[A-Z]/)
	.add_pattern_lexeme('number', /^[0-9]/);
